In [ ]:


import os
import sys
import subprocess

# Cài certifi nếu máy chưa có
try:
    import certifi
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "certifi"])
    import certifi

# Lấy đường dẫn certificate đúng của certifi
cert_path = certifi.where()

# Ép Python/requests dùng certificate đúng
os.environ["REQUESTS_CA_BUNDLE"] = cert_path
os.environ["SSL_CERT_FILE"] = cert_path

print("Đã set SSL certificate thành:")
print(cert_path)

print("\nKiểm tra biến môi trường hiện tại:")
print("REQUESTS_CA_BUNDLE =", os.environ.get("REQUESTS_CA_BUNDLE"))

print("SSL_CERT_FILE =", os.environ.get("SSL_CERT_FILE"))

Đã set SSL certificate thành:
c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\certifi\cacert.pem

Kiểm tra biến môi trường hiện tại:
REQUESTS_CA_BUNDLE = c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\certifi\cacert.pem
SSL_CERT_FILE = c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages\certifi\cacert.pem

In [131]:
import sys

!{sys.executable} -m pip install -U vnstock_data

ERROR: Could not find a version that satisfies the requirement vnstock_data (from versions: none)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for vnstock_data

In [132]:
pip install -U vnstock

Requirement already satisfied: vnstock in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (4.0.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: requests in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnstock) (2.32.3)
Requirement already satisfied: beautifulsoup4 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnstock) (4.13.3)
Requirement already satisfied: pandas in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnstock) (2.2.3)
Requirement already satisfied: seaborn in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnstock) (0.13.2)
Requirement already satisfied: openpyxl in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnstock) (3.1.5)
Requirement already satisfied: pydantic in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnstock) (2.11.5)
Requirement already satisfied: psutil in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnstock) (6.1.1)
Requirement already satisfied: packaging>=20.0 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnstock) (24.2)
Requirement already satisfied: importlib-metadata>=1.0 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnstock) (8.7.0)
Requirement already satisfied: tenacity in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnstock) (9.1.2)
Requirement already satisfied: vnai>=2.4.8 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnstock) (2.4.8)
Requirement already satisfied: vnstock_ezchart>=0.0.3 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnstock) (0.0.3)
Requirement already satisfied: pytz in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnstock) (2025.1)
Requirement already satisfied: zipp>=3.20 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from importlib-metadata>=1.0->vnstock) (3.22.0)
Requirement already satisfied: cffi>=1.17.1 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnai>=2.4.8->vnstock) (2.0.0)
Requirement already satisfied: pycparser in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from cffi>=1.17.1->vnai>=2.4.8->vnstock) (2.22)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->vnstock) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->vnstock) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->vnstock) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->vnstock) (2025.1.31)
Requirement already satisfied: squarify in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnstock_ezchart>=0.0.3->vnstock) (0.4.4)
Requirement already satisfied: wordcloud in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from vnstock_ezchart>=0.0.3->vnstock) (1.9.4)
Requirement already satisfied: soupsieve>1.2 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from beautifulsoup4->vnstock) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from beautifulsoup4->vnstock) (4.12.2)
Requirement already satisfied: et-xmlfile in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from openpyxl->vnstock) (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas->vnstock) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas->vnstock) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas->vnstock) (2025.1)
Requirement already satisfied: six>=1.5 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas->vnstock) (1.17.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic->vnstock) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic->vnstock) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic->vnstock) (0.4.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from seaborn->vnstock) (3.10.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (4.58.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (1.4.8)
Requirement already satisfied: pillow>=8 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn->vnstock) (3.2.3)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [133]:
!pip show vnstock

Name: vnstock
Version: 4.0.2
Summary: A beginner-friendly yet powerful Python toolkit for financial analysis and automation — built to make modern investing accessible to everyone
Home-page:
Author:
Author-email: Thinh Vu <support@vnstocks.com>
License: Custom: Personal, research, non-commercial; contact support@vnstocks.com for other use
Location: C:\Users\USER\AppData\Local\Programs\Python\Python313\Lib\site-packages
Requires: beautifulsoup4, importlib-metadata, openpyxl, packaging, pandas, psutil, pydantic, pytz, requests, seaborn, tenacity, vnai, vnstock_ezchart
Required-by: vnstock_ezchart

In [134]:
from vnstock import Vnstock
from vnstock import Quote
from vnstock import Listing
from vnstock import Finance
from vnstock import Company
import time
import pandas as pd
listing = Listing(source='VCI')

In [135]:
industry_df = listing.symbols_by_industries()

industry_df

,symbol,organ_name,com_type_code,icb_level,icb_code,icb_name
0,A32,Công ty Cổ phần 32,CT,1,3000,Hàng Tiêu dùng
1,A32,Công ty Cổ phần 32,CT,2,3700,Hàng cá nhân & Gia dụng
2,A32,Công ty Cổ phần 32,CT,3,3760,Hàng cá nhân
3,A32,Công ty Cổ phần 32,CT,4,3765,Giầy dép
4,AAA,Công ty Cổ phần Nhựa An Phát Xanh,CT,1,1000,Nguyên vật liệu
...,...,...,...,...,...,...
7691,YEG,Công ty Cổ phần Tập đoàn Yeah1,CT,4,5553,Giải trí & Truyền thông
7692,YTC,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...,CT,1,4000,Dược phẩm và Y tế
7693,YTC,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...,CT,2,4500,Y tế
7694,YTC,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...,CT,3,4530,Thiết bị và Dịch vụ Y tế
7695,YTC,Công ty Cổ phần Xuất nhập khẩu Y tế Thành phố ...,CT,4,4537,Dụng cụ y tế

In [136]:
target_industry = "Điện, nước & xăng dầu khí đốt"

filtered_df = industry_df[
    industry_df["icb_name"].astype(str).str.contains(
        target_industry,
        case=False,
        na=False,
        regex=False
    )
].copy()

filtered_df

,symbol,organ_name,com_type_code,icb_level,icb_code,icb_name
277,ASP,Công ty Cổ phần Tập đoàn Dầu khí An Pha,CT,2,7500,"Điện, nước & xăng dầu khí đốt"
313,AVC,Công ty Cổ phần Thủy điện A Vương,CT,2,7500,"Điện, nước & xăng dầu khí đốt"
429,BDW,Công ty Cổ phần Cấp thoát nước Bình Định,CT,2,7500,"Điện, nước & xăng dầu khí đốt"
445,BGE,Công ty Cổ phần BCG Energy,CT,2,7500,"Điện, nước & xăng dầu khí đốt"
457,BGW,Công ty Cổ phần Nước sạch Bắc Giang,CT,2,7500,"Điện, nước & xăng dầu khí đốt"
...,...,...,...,...,...,...
7405,VPW,Công ty Cổ phần Cấp thoát nước số 1 Vĩnh Phúc,CT,2,7500,"Điện, nước & xăng dầu khí đốt"
7449,VSH,Công ty Cổ phần Thủy điện Vĩnh Sơn - Sông Hinh,CT,2,7500,"Điện, nước & xăng dầu khí đốt"
7585,VWS,Công ty Cổ phần Nước và Môi trường Việt Nam,CT,2,7500,"Điện, nước & xăng dầu khí đốt"
7613,WTB,Công ty Cổ Phần Thuỷ Điện To Buông,CT,2,7500,"Điện, nước & xăng dầu khí đốt"
7665,XMP,Công ty Cổ phần Thủy điện Xuân Minh,CT,2,7500,"Điện, nước & xăng dầu khí đốt"

In [137]:
for i in filtered_df["symbol"].unique():
    print(i)

ASP
AVC
BDW
BGE
BGW
BHA
BLW
BMF
BNW
BSA
BTP
BTW
BWA
BWE
BWS
CCI
CGC
CHP
CHS
CLW
CMW
CNG
CTW
CVH
DBW
DDG
DKW
DLM
DMS
DNA
DNC
DNH
DNN
DNW
DRL
DTE
DTK
DTV
DVC
DWC
DWS
EAD
GAS
GCB
GDW
GE2
GEG
GHC
GLW
GSM
HDW
HFC
HGW
HIO
HJS
HNA
HND
HPD
HPW
HTC
HTW
HWS
ISH
KHP
KHW
KTW
KWA
LAW
LCW
LDW
LKW
LWS
MTG
NAW
NBP
NBT
NBW
ND2
NDW
NLS
NNT
NQB
NQN
NQT
NS2
NS3
NSL
NT2
NTH
NTW
NVP
PBK
PCG
PDT
PEG
PGC
PGD
PGS
PGV
PIC
PJC
PJS
PMG
PMW
PND
POB
POV
POW
PPC
PPT
PPY
PSH
PTH
PTX
PVG
PWS
QNW
QPH
QTP
REE
S4A
SBA
SBH
SEB
SFC
SHP
SII
SJD
SMA
SP2
STW
SVH
TAW
TBC
TBW
TDB
TDG
TDM
TDW
THN
THW
TLP
TMC
TMP
TNW
TOW
TQW
TTA
TTE
TVW
UIC
UPC
VAV
VCP
VCW
VLW
VMG
VPD
VPW
VSH
VWS
WTB
XMP

In [138]:
finance = Finance(symbol="ASP", source= "KBS")
bcdkt = finance.balance_sheet(period= "year")
bcdkt.head()

,item,item_id,2025-Năm,2024-Năm,2023-Năm,2022-Năm
0,TÀI SẢN,assets,NaN,NaN,NaN,NaN
1,A. TÀI SẢN NGẮN HẠN,a.short_term_assets,673070424.0,809260745.0,1.309627e+09,1.097024e+09
2,I. Tiền và các khoản tương đương tiền,i.cash_and_cash_equivalents,76813856.0,189235486.0,2.159892e+08,1.227334e+08
3,1. Tiền,n_1.cash,76813856.0,129235486.0,2.159892e+08,8.631725e+07
4,2. Các khoản tương đương tiền,n_2.cash_equivalents,NaN,60000000.0,NaN,3.641620e+07

In [139]:
ts = bcdkt.loc[
    bcdkt["item"].isin(["A. TÀI SẢN NGẮN HẠN", "B. TÀI SẢN DÀI HẠN"]),
    '2025-Năm'
].sum()

print(ts)

1327198991.0

In [140]:
skipped = []

In [141]:
symbols = filtered_df["symbol"].dropna().unique()

for i in symbols:
    try:
        finance = Finance(symbol=i, source="KBS")
        bcdkt = finance.balance_sheet(period="year")
        if "2025-Năm" not in bcdkt.columns:
            print(i, "Không có BCTC 2025")
            skipped.append(i)
            continue

        ts = bcdkt.loc[
            bcdkt["item"].isin(["A. TÀI SẢN NGẮN HẠN", "B. TÀI SẢN DÀI HẠN"]),
            "2025-Năm"
        ].sum()
        # Bỏ qua nếu không có dữ liệu tài sản
        if pd.isna(ts) or ts == 0:
            print(i, "Không có dữ liệu tài sản 2025")
            skipped.append(i)
            continue

        results.append({
            "symbol": i,
            "total_assets_2025": ts
        })

        print(i, ts) 

        time.sleep(1.2)

    except SystemExit:
        print("Đụng rate limit, chờ 20 giây rồi chạy tiếp...")
        time.sleep(20)
        continue

    except Exception as e:
        print(f"Lỗi mã {i}: {e}")
        skipped.append({"symbol": i, "reason": str(e)})
        time.sleep(1.2)

ASP 1327198991.0
AVC 1341897534.0
BDW 458199640.0
BGE Không có BCTC 2025
BGW 243006548.0
BHA 1464983910.0
BLW Không có BCTC 2025
BMF 643997969.0
BNW 928816308.0
BSA 1247828985.0
BTP 1218678652.0
BTW 384095302.0
BWA 110436991.0
BWE 15148255852.0
BWS 1240958007.0
CCI 1093993676.0
CGC Không có BCTC 2025
CHP 2616813677.0
CHS 478310587.0
CLW 535394275.0
CMW 334080434.0
CNG 1720484867.0
CTW 947635635.0
CVH Không có BCTC 2025
DBW Không có BCTC 2025
DDG 1358221308.0
DKW Không có BCTC 2025
DLM Không có BCTC 2025
DMS 81399047.0
DNA 1652966653.0
DNC 254040866.0
DNH 7423241353.0
DNN 1562688701.0
DNW 3442157723.0
DRL 127286396.0
DTE 508435454.0
DTK 15337038379.0
DTV Không có BCTC 2025
DVC 351472602.0
DWC 863819311.0
DWS 1071160435.0
EAD Không có BCTC 2025
GAS 93568198109.0
GCB 425434696.0
GDW 340167822.0
GE2 Không có BCTC 2025
GEG 15110888031.0
GHC 1486268189.0
GLW 213186645.0
GSM 748920543.0
HDW 911990850.0
HFC 231300096.0
HGW Không có BCTC 2025
HIO 447578136.0
HJS 357537280.0
HNA 3969431150.0
HND 7355002050.0
HPD 168028799.0
HPW 2094006665.0
HTC 599893186.0
HTW Không có BCTC 2025
HWS 1945559442.0
ISH 648614901.0
KHP 2168922037.0
KHW 630779321.0
KTW Không có BCTC 2025
KWA Không có BCTC 2025
LAW 411390020.0
LCW Không có BCTC 2025
LDW 1179680760.0
LKW 99239977.0
LWS Không có BCTC 2025
MTG 182087816.0
NAW 753204859.0
NBP 269685156.0
NBT 528918499.0
NBW 331272364.0
ND2 1486476394.0
NDW 562733365.0
NLS 155795989.0
NNT 571688710.0
NQB 247252210.0
NQN 1231469451.0
NQT 326059221.0
NS2 1638631523.0
NS3 Không có BCTC 2025
NSL 178026530.0
NT2 9273311226.0
NTH 191393399.0
NTW 200201434.0
NVP 193728585.0
PBK Không có BCTC 2025
PCG 204498384.0
PDT Không có BCTC 2025
PEG 1207072401.0
PGC 3151673810.0
PGD 3574790891.0
PGS 2553835834.0
PGV 55031797692.0
PIC 443995084.0
PJC 273838486.0
PJS 232436774.0
PMG 1520491470.0
PMW 673133549.0
PND 124422494.0
POB 183170560.0
POV 433006688.0
POW 88611929064.0
PPC 5246604576.0
PPT 506006126.0
PPY 302867392.0
PSH 10506141909.0
PTH 110956726.0
PTX 281662317.0
PVG 1525857291.0
PWS 477242647.0
QNW 301438343.0
QPH 378728608.0
QTP 7775427091.0
REE 40074851709.0
S4A 1047332595.0
SBA 1162368116.0
SBH 2212594332.0
SEB 703508565.0
SFC 277781201.0
SHP 1469965044.0
SII 2930962245.0
SJD 1379818711.0
SMA 408353363.0
SP2 556992920.0
STW 275686646.0
SVH 573586769.0
TAW 173289917.0
TBC 1653267349.0
TBW 257732156.0
TDB 118269491.0
TDG 961389293.0
TDM 3396116489.0
TDW 716083959.0
THN 715107888.0
THW 138357830.0
TLP 9485990055.0
TMC 380370546.0
TMP 2252005535.0
TNW 825483111.0
TOW 221147682.0
TQW 113708022.0
TTA 4149551242.0
TTE 797066496.0
TVW Không có BCTC 2025
UIC 821528629.0
UPC 211803841.0
VAV 1325096430.0
VCP 6315038534.0
VCW Không có BCTC 2025
VLW 627133003.0
VMG 105752675.0
VPD 1780695197.0
VPW 307362000.0
VSH 8171336734.0
VWS 142402923.0
WTB Không có BCTC 2025
XMP 368019944.0

In [142]:
assets_df = (
    assets_df
    .sort_values("total_assets_2025", ascending=False)
    .drop_duplicates(subset="symbol", keep="first")
    .reset_index(drop=True)
)

top15 = assets_df.head(15)

top15

   symbol  total_assets_2025
0     GAS       9.356820e+10
1     POW       8.861193e+10
2     PGV       5.503180e+10
3     REE       4.007485e+10
4     DTK       1.533704e+10
5     BWE       1.514826e+10
6     GEG       1.511089e+10
7     PSH       1.050614e+10
8     TLP       9.485990e+09
9     NT2       9.273311e+09
10    VSH       8.171337e+09
11    QTP       7.775427e+09
12    DNH       7.423241e+09
13    HND       7.355002e+09
14    VCP       6.315039e+09

In [143]:
# Danh sách 15 doanh nghiệp có vốn hóa lớn nhất ngành
top15_list = pd.merge(top15,filtered_df[['symbol', 'organ_name', 'icb_name']], on = 'symbol', how = 'left')
top15_list

,symbol,total_assets_2025,organ_name,icb_name
0,GAS,9.356820e+10,Tổng Công ty Khí Việt Nam - Công ty Cổ phần,"Điện, nước & xăng dầu khí đốt"
1,POW,8.861193e+10,Tổng Công ty Điện lực Dầu khí Việt Nam - CTCP,"Điện, nước & xăng dầu khí đốt"
2,PGV,5.503180e+10,Tổng Công ty Phát điện 3 - Công ty Cổ phần,"Điện, nước & xăng dầu khí đốt"
3,REE,4.007485e+10,Công ty Cổ phần Cơ điện Lạnh,"Điện, nước & xăng dầu khí đốt"
4,DTK,1.533704e+10,Tổng Công ty Điện lực TKV - Công ty Cổ phần,"Điện, nước & xăng dầu khí đốt"
5,BWE,1.514826e+10,Công ty Cổ phần - Tổng công ty Nước - Môi trườ...,"Điện, nước & xăng dầu khí đốt"
6,GEG,1.511089e+10,Công ty Cổ phần Điện Gia Lai,"Điện, nước & xăng dầu khí đốt"
7,PSH,1.050614e+10,Công ty Cổ phần Thương mại Đầu tư Dầu khí Nam ...,"Điện, nước & xăng dầu khí đốt"
8,TLP,9.485990e+09,Tổng Công ty Thương mại Xuất nhập khẩu Thanh L...,"Điện, nước & xăng dầu khí đốt"
9,NT2,9.273311e+09,Công ty Cổ phần Điện lực Dầu khí Nhơn Trạch 2,"Điện, nước & xăng dầu khí đốt"
10,VSH,8.171337e+09,Công ty Cổ phần Thủy điện Vĩnh Sơn - Sông Hinh,"Điện, nước & xăng dầu khí đốt"
11,QTP,7.775427e+09,Công ty Cổ phần Nhiệt điện Quảng Ninh,"Điện, nước & xăng dầu khí đốt"
12,DNH,7.423241e+09,Công ty Cổ phần Thủy điện Đa Nhim - Hàm Thuận ...,"Điện, nước & xăng dầu khí đốt"
13,HND,7.355002e+09,Công ty Cổ phần Nhiệt điện Hải Phòng,"Điện, nước & xăng dầu khí đốt"
14,VCP,6.315039e+09,Công ty Cổ phần Xây dựng và Năng lượng VCP,"Điện, nước & xăng dầu khí đốt"

In [158]:
company = Company(symbol='VCP', source='KBS')
company.ownership()

  owner_type  ownership_percentage  shares_owned          update_date
0     CĐ lớn                  59.5      49860900  2024-12-31T00:00:00
1    CĐ khác                  40.5      33928758  2024-12-31T00:00:00

In [157]:
# Cổ đông lớn nhất
ownership_results = []

for n in top15_list["symbol"].dropna().astype(str).str.strip().str.upper().drop_duplicates():
    try:
        company = Company(symbol= n, source='KBS')
        own = company.ownership()

        top_holder = (
            own.dropna(subset = ["ownership_percentage"])
            .sort_values("ownership_percentage", ascending = False)
            .head(1))
        row = top_holder.iloc[0]

        ownership_results.append({
            "symbol": n,
            "owner_type": row["owner_type"],
            "ownership_percentage": row["ownership_percentage"],
            "shares_owned": row["shares_owned"],
            "update_date": row["update_date"]
        })
    except Exception as e:
        print(f"Lỗi {n}: {e}")

ownership_df = pd.DataFrame(ownership_results)

ownership_df

,symbol,owner_type,ownership_percentage,shares_owned,update_date
0,GAS,CĐ Nhà nước,95.76,2310692875,2025-12-31T00:00:00
1,POW,CĐ Nhà nước,79.94,2227848357,2025-12-31T00:00:00
2,PGV,CĐ Nhà nước,99.19,1114422994,2025-12-31T00:00:00
3,REE,Tổ chức nước ngoài,48.70,263766016,2026-02-27T00:00:00
4,DTK,CĐ Nhà nước,99.27,677808500,2025-12-31T00:00:00
5,BWE,Tổ chức trong nước,74.14,163055097,2025-12-31T00:00:00
6,GEG,CĐ trong nước,63.35,226995254,2025-12-31T00:00:00
7,PSH,CĐ trong nước khác,56.71,71563680,2024-12-31T00:00:00
8,TLP,Cá nhân trong nước,62.50,147884500,2024-12-31T00:00:00
9,NT2,Tổ chức trong nước,73.43,211397896,2025-12-31T00:00:00
10,VSH,Tổ chức trong nước,57.76,136441367,2025-12-31T00:00:00
11,QTP,Tổ chức trong nước,89.16,401227016,2025-12-31T00:00:00
12,DNH,Tổ chức trong nước,99.93,422103100,2024-12-31T00:00:00
13,HND,CĐ nắm trên 5% số CP,93.18,465900000,2025-12-31T00:00:00
14,VCP,CĐ lớn,59.50,49860900,2024-12-31T00:00:00

In [162]:
List_portfolio = pd.merge(top15_list, ownership_df[['symbol', 'owner_type', 'ownership_percentage']], on = "symbol", how = "left")
List_portfolio

,symbol,total_assets_2025,organ_name,icb_name,owner_type,ownership_percentage
0,GAS,9.356820e+10,Tổng Công ty Khí Việt Nam - Công ty Cổ phần,"Điện, nước & xăng dầu khí đốt",CĐ Nhà nước,95.76
1,POW,8.861193e+10,Tổng Công ty Điện lực Dầu khí Việt Nam - CTCP,"Điện, nước & xăng dầu khí đốt",CĐ Nhà nước,79.94
2,PGV,5.503180e+10,Tổng Công ty Phát điện 3 - Công ty Cổ phần,"Điện, nước & xăng dầu khí đốt",CĐ Nhà nước,99.19
3,REE,4.007485e+10,Công ty Cổ phần Cơ điện Lạnh,"Điện, nước & xăng dầu khí đốt",Tổ chức nước ngoài,48.70
4,DTK,1.533704e+10,Tổng Công ty Điện lực TKV - Công ty Cổ phần,"Điện, nước & xăng dầu khí đốt",CĐ Nhà nước,99.27
5,BWE,1.514826e+10,Công ty Cổ phần - Tổng công ty Nước - Môi trườ...,"Điện, nước & xăng dầu khí đốt",Tổ chức trong nước,74.14
6,GEG,1.511089e+10,Công ty Cổ phần Điện Gia Lai,"Điện, nước & xăng dầu khí đốt",CĐ trong nước,63.35
7,PSH,1.050614e+10,Công ty Cổ phần Thương mại Đầu tư Dầu khí Nam ...,"Điện, nước & xăng dầu khí đốt",CĐ trong nước khác,56.71
8,TLP,9.485990e+09,Tổng Công ty Thương mại Xuất nhập khẩu Thanh L...,"Điện, nước & xăng dầu khí đốt",Cá nhân trong nước,62.50
9,NT2,9.273311e+09,Công ty Cổ phần Điện lực Dầu khí Nhơn Trạch 2,"Điện, nước & xăng dầu khí đốt",Tổ chức trong nước,73.43
10,VSH,8.171337e+09,Công ty Cổ phần Thủy điện Vĩnh Sơn - Sông Hinh,"Điện, nước & xăng dầu khí đốt",Tổ chức trong nước,57.76
11,QTP,7.775427e+09,Công ty Cổ phần Nhiệt điện Quảng Ninh,"Điện, nước & xăng dầu khí đốt",Tổ chức trong nước,89.16
12,DNH,7.423241e+09,Công ty Cổ phần Thủy điện Đa Nhim - Hàm Thuận ...,"Điện, nước & xăng dầu khí đốt",Tổ chức trong nước,99.93
13,HND,7.355002e+09,Công ty Cổ phần Nhiệt điện Hải Phòng,"Điện, nước & xăng dầu khí đốt",CĐ nắm trên 5% số CP,93.18
14,VCP,6.315039e+09,Công ty Cổ phần Xây dựng và Năng lượng VCP,"Điện, nước & xăng dầu khí đốt",CĐ lớn,59.50

GAS

POW

PGV

REE

DTK

BWE

GEG

PSH

TLP

NT2

VSH

QTP

DNH

HND

VCP